AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-qa-lambda

  Sample SAM Template for simple-qa-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SimpleQADockerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: ./
      MemorySize: 512
      Timeout: 25
      Architectures:
        - x86_64
      Events:
        SimpleQA:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /qa
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: latest

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimpleQAApi:
    Description: "API Gateway endpoint URL for Prod stage for Simple QA function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/qa/"
  SimpleQADockerLambdaFunction:
    Description: "Simple QA Lambda Function ARN"
    Value: !GetAtt SimpleQADockerLambdaFunction.Arn
  SimpleQADockerLambdaFunction:
    Description: "Implicit IAM Role created for Simple QA function"
    Value: !GetAtt SimpleQADockerLambdaFunctionRole.Arn
